
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

before_install:
<<<<<<< HEAD
<<<<<<< HEAD
  - julia --project --color=yes -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/FrameFunVC/FrameFunRegistry"));'
  - julia --project --color=yes -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"));'
=======
    script:
       julia --project=. --color=yes -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/FrameFunVC/FrameFunRegistry"));'
>>>>>>> Modify Travis YML to find FrameFun Repo
=======
    script:
       - julia --project=. --color=yes -e 'using Pkg; Pkg.Registry.add("https://github.com/vincentcp/FrameFunRegistry");'
>>>>>>> Add FrameFun repo to Travis routine

notifications:
  email: false

codecov: true
coveralls: true
